### PR TITLE
nb - added comments

### LINKED ISSUE #32: Create Mockup Comments For Water Sources
**User Story:**

As a User, I want to be able to leave comments and read comments in addition to my ratings, so I can better decide if a water source is good. 

**Explanation:**

Connected to #31 in that both relate to rating / giving feedback on water sources, but rating a water source and creating a comment should probably be kept separate for now. 
(We're low on time, so a mockup made out of a recycler view would suffice).

### PR DESCRIPTION
**Pull request by nicholasbrown1**
Closes #32. The water info fragment displays comments by other users about the fountain. The comments are stored in a firebase collection called comments. The field to type comments and the enter button are hidden when the user is not logged in, but other comments are visible. Comments are sorted by most recent first using a timestamp stored in the firebase that corresponds to the value of System.currentTimeMillis() when the comment is uploaded.

### CODE REVIEW

**Comment by J-Miller1** [comment]
LGTM. Everything looks good and seems to work as intended on my tablet.

**Review by J-Miller1 — APPROVED** [review]
LGTM. Everything looks good and seems to work as intended on my tablet.

**Comment by DLohn** [comment]
LGTM!

**Review by DLohn — APPROVED** [review]
LGTM!

**Pull request merged**
